<?php

namespace App\Services;

use App\Models\AdmissionApplication;
use App\Models\AcademicYears;
use App\Models\Classes;
use App\Models\Section;
use App\Models\Student;
use App\Models\Guardian;
use App\Models\StudentEnrollment;
use Illuminate\Support\Facades\DB;
use Illuminate\Validation\ValidationException;

class AdmissionService
{
    /**
     * Create a new admission application.
     *
     * Application number is always generated server-side.
     */
    public function create(array $data): AdmissionApplication
    {
        $schoolId = (int) auth()->user()->school_id;

        $data['school_id'] = $schoolId;
        $data['created_by'] = auth()->id();

        // Application number is generated by the system.
        $data['application_number'] = $this->nextApplicationNumber($schoolId);

        $data['applied_at'] = $data['applied_at'] ?? now();

        $this->validatePlacement($data, $schoolId);

        return AdmissionApplication::create($data);
    }

    /**
     * Update an existing admission application.
     */
    public function update(
        AdmissionApplication $application,
        array $data
    ): AdmissionApplication {
        $this->ensureSchool($application);

        // Converted applications should not be edited normally.
        if ($application->status === 'converted') {
            throw ValidationException::withMessages([
                'status' => 'Converted admission applications cannot be edited.',
            ]);
        }

        $schoolId = (int) $application->school_id;

        $this->validatePlacement($data, $schoolId);

        // These fields are controlled by the service/database.
        unset(
            $data['school_id'],
            $data['created_by'],
            $data['application_number'],
            $data['student_id'],
            $data['processed_at']
        );

        $application->update($data);

        return $application->fresh();
    }

    /**
     * Accept an admission application.
     */
    public function accept(
        AdmissionApplication $application
    ): AdmissionApplication {
        $this->ensureSchool($application);

        if ($application->student_id) {
            throw ValidationException::withMessages([
                'status' => 'This application has already been converted.',
            ]);
        }

        if (
            ! in_array(
                $application->status,
                ['submitted', 'under_review', 'accepted'],
                true
            )
        ) {
            throw ValidationException::withMessages([
                'status' => 'Only a submitted, under-review, or accepted application can be accepted.',
            ]);
        }

        $application->update([
            'status' => 'accepted',
            'processed_at' => now(),
        ]);

        return $application->fresh();
    }

    /**
     * Convert an admission application into a student.
     */
    public function convertToStudent(
        AdmissionApplication $application
    ): Student {
        $this->ensureSchool($application);

        // Idempotent conversion.
        if ($application->student_id) {
            return $application->student()->firstOrFail();
        }

        if (
            ! $application->academic_year_id ||
            ! $application->class_id
        ) {
            throw ValidationException::withMessages([
                'placement' => 'Academic year and class are required before conversion.',
            ]);
        }

        if (
            ! in_array(
                $application->status,
                ['accepted'],
                true
            )
        ) {
            throw ValidationException::withMessages([
                'status' => 'Only an accepted admission application can be converted to a student.',
            ]);
        }

        $schoolId = (int) $application->school_id;

        return DB::transaction(
            function () use ($application, $schoolId) {
                /*
                 * Revalidate placement inside the transaction.
                 */
                $this->validatePlacement(
                    [
                        'academic_year_id' => $application->academic_year_id,
                        'class_id' => $application->class_id,
                        'section_id' => $application->section_id,
                    ],
                    $schoolId
                );

                /*
                 * Create student.
                 */
                $student = Student::create([
                    'school_id' => $schoolId,

                    'student_number' => $this->nextStudentNumber(
                        $schoolId
                    ),

                    'admission_number' =>
                        $application->application_number,

                    'first_name' => $application->first_name,
                    'middle_name' => $application->middle_name,
                    'last_name' => $application->last_name,

                    'date_of_birth' =>
                        $application->date_of_birth,

                    'gender' => $application->gender,
                    'phone' => $application->phone,

                    'admission_date' => today(),

                    'status' => 'active',

                    'address' => $application->address,

                    'created_by' => auth()->id(),
                    'updated_by' => auth()->id(),
                ]);

                /*
                 * Create and link guardian when supplied.
                 */
                if ($application->guardian_name) {
                    $parts = preg_split(
                        '/\s+/',
                        trim($application->guardian_name)
                    );

                    $first = array_shift($parts) ?: 'Guardian';
                    $last = count($parts)
                        ? array_pop($parts)
                        : 'Guardian';

                    $middle = count($parts)
                        ? implode(' ', $parts)
                        : null;

                    $guardian = Guardian::create([
                        'school_id' => $schoolId,

                        'guardian_number' =>
                            $this->nextGuardianNumber($schoolId),

                        'first_name' => $first,
                        'middle_name' => $middle,
                        'last_name' => $last,

                        'phone' => $application->guardian_phone,
                        'email' => $application->guardian_email,
                    ]);

                    $student->guardians()->attach(
                        $guardian->id,
                        [
                            'relationship' =>
                                $application->guardian_relationship
                                ?: 'Guardian',

                            'is_primary' => true,
                            'is_emergency_contact' => true,
                        ]
                    );
                }

                /*
                 * Retrieve and verify academic hierarchy.
                 */
                $year = AcademicYears::query()
                    ->where('id', $application->academic_year_id)
                    ->where('school_id', $schoolId)
                    ->firstOrFail();

                $class = Classes::query()
                    ->where('id', $application->class_id)
                    ->where('school_id', $schoolId)
                    ->firstOrFail();

                if ($application->section_id) {
                    Section::query()
                        ->where('id', $application->section_id)
                        ->where('class_id', $class->id)
                        ->firstOrFail();
                }

                /*
                 * Initial enrollment.
                 */
                StudentEnrollment::create([
                    'school_id' => $schoolId,
                    'student_id' => $student->id,

                    'academic_year_id' => $year->id,

                    'term_id' => null,

                    'class_id' => $class->id,
                    'section_id' => $application->section_id,

                    'enrollment_number' =>
                        'ENR-' .
                        date('Y') .
                        '-' .
                        str_pad(
                            (string) $student->id,
                            5,
                            '0',
                            STR_PAD_LEFT
                        ),

                    'enrollment_date' => today(),

                    'status' => 'active',

                    'created_by' => auth()->id(),
                    'updated_by' => auth()->id(),
                ]);

                /*
                 * Mark application converted.
                 */
                $application->update([
                    'status' => 'converted',
                    'student_id' => $student->id,
                    'processed_at' => now(),
                ]);

                return $student;
            }
        );
    }

    /**
     * Validate academic placement against the school.
     */
    private function validatePlacement(
        array $data,
        int $schoolId
    ): void {
        /*
         * Academic year.
         */
        if (! empty($data['academic_year_id'])) {
            $exists = AcademicYears::query()
                ->where('id', $data['academic_year_id'])
                ->where('school_id', $schoolId)
                ->exists();

            if (! $exists) {
                throw ValidationException::withMessages([
                    'academic_year_id' =>
                        'The selected academic year does not belong to this school.',
                ]);
            }
        }

        /*
         * Class.
         */
        if (! empty($data['class_id'])) {
            $exists = Classes::query()
                ->where('id', $data['class_id'])
                ->where('school_id', $schoolId)
                ->exists();

            if (! $exists) {
                throw ValidationException::withMessages([
                    'class_id' =>
                        'The selected class does not belong to this school.',
                ]);
            }
        }

        /*
         * Section must belong to the selected class.
         */
        if (! empty($data['section_id'])) {
            $classId = $data['class_id'] ?? null;

            if (! $classId) {
                throw ValidationException::withMessages([
                    'section_id' =>
                        'Class is required when a section is selected.',
                ]);
            }

            $exists = Section::query()
                ->where('id', $data['section_id'])
                ->where('class_id', $classId)
                ->exists();

            if (! $exists) {
                throw ValidationException::withMessages([
                    'section_id' =>
                        'The selected section does not belong to the selected class.',
                ]);
            }
        }
    }

    /**
     * Ensure admission application belongs to authenticated school.
     */
    private function ensureSchool(
        AdmissionApplication $application
    ): void {
        abort_unless(
            (int) $application->school_id ===
            (int) auth()->user()->school_id,
            403,
            'Unauthorized admission application.'
        );
    }

    /**
     * Generate next application number for the school.
     */
    private function nextApplicationNumber(
        int $schoolId
    ): string {
        $next = AdmissionApplication::withTrashed()
            ->where('school_id', $schoolId)
            ->count() + 1;

        return 'APP-' .
            date('Y') .
            '-' .
            str_pad(
                (string) $next,
                5,
                '0',
                STR_PAD_LEFT
            );
    }

    /**
     * Generate next student number for the school.
     */
    private function nextStudentNumber(
        int $schoolId
    ): string {
        $next = Student::query()
            ->where('school_id', $schoolId)
            ->count() + 1;

        return 'STU-' .
            date('Y') .
            '-' .
            str_pad(
                (string) $next,
                5,
                '0',
                STR_PAD_LEFT
            );
    }

    /**
     * Generate next guardian number for the school.
     */
    private function nextGuardianNumber(
        int $schoolId
    ): string {
        $next = Guardian::withTrashed()
            ->where('school_id', $schoolId)
            ->count() + 1;

        return 'GDN-' .
            date('Y') .
            '-' .
            str_pad(
                (string) $next,
                5,
                '0',
                STR_PAD_LEFT
            );
    }
}