@extends('backend.layout.default')
@section('content')
<div class="container-fluid">
<div class="page-title-box d-sm-flex align-items-center justify-content-between"><h4>Scholarship Details</h4><ol class="breadcrumb m-0"><li class="breadcrumb-item">Finance</li><li class="breadcrumb-item"><a href="{{ route('admin.scholarships.index') }}">Scholarships</a></li><li class="breadcrumb-item active">{{ $scholarship->name }}</li></ol></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif@if(session('error'))<div class="alert alert-danger">{{ session('error') }}</div>@endif
<div class="row"><div class="col-lg-5"><div class="card"><div class="card-header"><h5 class="card-title mb-0">Scholarship Information</h5></div><div class="card-body"><dl class="row mb-0"><dt class="col-sm-5">Name</dt><dd class="col-sm-7">{{ $scholarship->name }}</dd><dt class="col-sm-5">Type</dt><dd class="col-sm-7">{{ ucfirst($scholarship->type) }}</dd><dt class="col-sm-5">Value</dt><dd class="col-sm-7 fw-semibold">{{ $scholarship->formatted_value }}</dd><dt class="col-sm-5">Status</dt><dd class="col-sm-7">@if($scholarship->is_active)<span class="badge bg-success">Active</span>@else<span class="badge bg-secondary">Inactive</span>@endif</dd><dt class="col-sm-5">Assigned Fees</dt><dd class="col-sm-7">{{ $scholarship->student_fees_count }}</dd><dt class="col-sm-5">Description</dt><dd class="col-sm-7">{{ $scholarship->description ?: '—' }}</dd></dl><div class="mt-4">@can('fees.manage')<a href="{{ route('admin.scholarships.edit',$scholarship) }}" class="btn btn-primary">Edit</a>@endcan <a href="{{ route('admin.scholarships.index') }}" class="btn btn-light">Back</a></div></div></div></div>
<div class="col-lg-7"><div class="card"><div class="card-header"><h5 class="card-title mb-0">Recent Student Fee Assignments</h5></div><div class="card-body"><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Student</th><th>Fee Structure</th><th>Amount</th><th>Discount</th><th>Status</th></tr></thead><tbody>@forelse($scholarship->studentFees as $fee)<tr><td>{{ $fee->student?->first_name }} {{ $fee->student?->last_name }}<div class="small text-muted">{{ $fee->student?->student_number }}</div></td><td>{{ $fee->feeStructure?->id ? 'Fee Structure #'.$fee->feeStructure->id : '—' }}</td><td>₹{{ number_format((float)$fee->amount,2) }}</td><td>₹{{ number_format((float)$fee->discount,2) }}</td><td><span class="badge bg-{{ $fee->status==='paid'?'success':($fee->status==='cancelled'?'secondary':'warning') }}">{{ ucfirst($fee->status) }}</span></td></tr>@empty<tr><td colspan="5" class="text-center text-muted py-4">No student fee assignments yet.</td></tr>@endforelse</tbody></table></div></div></div></div></div>
</div>
@endsection
