@extends('backend.layout.default')
@section('title', 'Academic Performance Report')
@section('content')
<div class="container-fluid">
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">Academic Performance</h4><p class="text-muted mb-0">Results, averages, grades and positions.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-danger" href="{{ route('admin.reports.academic-performance.pdf', request()->query()) }}">PDF</a><a class="btn btn-outline-success" href="{{ route('admin.reports.academic-performance.excel', request()->query()) }}">Excel</a></div></div>
<div class="row g-3 mb-3">@foreach([['Results',$performanceSummary['count']],['Average',$performanceSummary['average']],['Highest',$performanceSummary['highest']],['Lowest',$performanceSummary['lowest']]] as $s)<div class="col-md-3"><div class="card h-100"><div class="card-body"><div class="text-muted">{{ $s[0] }}</div><h4 class="mt-1 mb-0">{{ is_numeric($s[1]) && $s[0] !== 'Results' ? number_format($s[1],2) : number_format($s[1]) }}</h4></div></div></div>@endforeach</div>
<div class="card"><div class="card-body"><form method="GET" class="row g-2"><div class="col-md-4"><select class="form-select" name="academic_year_id"><option value="">All academic years</option>@foreach($academicYears as $year)<option value="{{ $year->id }}" @selected((string)request('academic_year_id')===(string)$year->id)>{{ $year->name }}</option>@endforeach</select></div><div class="col-md-4"><select class="form-select" name="examination_id"><option value="">All examinations</option>@foreach($examinations as $exam)<option value="{{ $exam->id }}" @selected((string)request('examination_id')===(string)$exam->id)>{{ $exam->name }} — {{ $exam->academicYear?->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="status"><option value="">All statuses</option>@foreach(['draft','approved','published'] as $v)<option value="{{ $v }}" @selected(request('status')===$v)>{{ ucfirst($v) }}</option>@endforeach</select></div><div class="col-md-1"><button class="btn btn-primary w-100">Go</button></div><div class="col-md-1"><a href="{{ route('admin.reports.academic-performance') }}" class="btn btn-light w-100">×</a></div></form></div></div>
<div class="row"><div class="col-xl-8"><div class="card"><div class="card-body table-responsive"><table class="table table-hover"><thead><tr><th>#</th><th>Student</th><th>Examination</th><th>Total</th><th>Average</th><th>Grade</th><th>Position</th><th>Status</th></tr></thead><tbody>@forelse($results as $r)<tr><td>{{ $results->firstItem()+$loop->index }}</td><td>{{ trim("{$r->student->first_name} {$r->student->middle_name} {$r->student->last_name}") }}</td><td>{{ $r->examination?->name }}</td><td>{{ number_format($r->total_score,2) }}</td><td>{{ number_format($r->average,2) }}</td><td>{{ $r->grade ?? '-' }}</td><td>{{ $r->position ?? '-' }}</td><td>{{ ucfirst($r->status) }}</td></tr>@empty<tr><td colspan="8" class="text-center text-muted py-4">No results found.</td></tr>@endforelse</tbody></table>{{ $results->links() }}</div></div></div><div class="col-xl-4"><div class="card"><div class="card-header"><h6 class="mb-0">Grade Distribution</h6></div><div class="card-body">@forelse($gradeDistribution as $g)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $g->grade ?? 'Not graded' }}</span><strong>{{ $g->total }}</strong></div>@empty<span class="text-muted">No grade data.</span>@endforelse</div></div></div></div>
</div>
@endsection
