@extends('backend.layout.default')
@section('title', 'Enrollment Report')
@section('content')
<div class="container-fluid">
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">Enrollment Report</h4><p class="text-muted mb-0">Historical student enrollment by academic period, class and section.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-danger" href="{{ route('admin.reports.enrollment.pdf', request()->query()) }}">PDF</a><a class="btn btn-outline-success" href="{{ route('admin.reports.enrollment.excel', request()->query()) }}">Excel</a></div></div>
<div class="card"><div class="card-body"><form method="GET" class="row g-2"><div class="col-md-3"><select class="form-select" name="academic_year_id"><option value="">All academic years</option>@foreach($academicYears as $year)<option value="{{ $year->id }}" @selected((string)request('academic_year_id')===(string)$year->id)>{{ $year->name }}</option>@endforeach</select></div><div class="col-md-3"><select class="form-select" name="class_id"><option value="">All classes</option>@foreach($classes as $class)<option value="{{ $class->id }}" @selected((string)request('class_id')===(string)$class->id)>{{ $class->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="section_id"><option value="">All sections</option>@foreach($sections as $section)<option value="{{ $section->id }}" @selected((string)request('section_id')===(string)$section->id)>{{ $section->name }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="status"><option value="">All statuses</option>@foreach(['active','completed','transferred','withdrawn'] as $v)<option value="{{ $v }}" @selected(request('status')===$v)>{{ ucfirst($v) }}</option>@endforeach</select></div><div class="col-md-1"><button class="btn btn-primary w-100">Go</button></div><div class="col-md-1"><a href="{{ route('admin.reports.enrollment') }}" class="btn btn-light w-100">×</a></div></form></div></div>
<div class="card"><div class="card-body table-responsive"><table class="table table-hover align-middle"><thead><tr><th>#</th><th>Enrollment No.</th><th>Student</th><th>Academic Year</th><th>Term</th><th>Class</th><th>Section</th><th>Date</th><th>Status</th></tr></thead><tbody>@forelse($enrollments as $e)<tr><td>{{ $enrollments->firstItem()+$loop->index }}</td><td>{{ $e->enrollment_number }}</td><td>{{ trim("{$e->student->first_name} {$e->student->middle_name} {$e->student->last_name}") }}</td><td>{{ $e->academicYear?->name }}</td><td>{{ $e->term?->name ?? '-' }}</td><td>{{ $e->class?->name }}</td><td>{{ $e->section?->name ?? '-' }}</td><td>{{ optional($e->enrollment_date)->format('d M Y') }}</td><td>{{ ucfirst($e->status) }}</td></tr>@empty<tr><td colspan="9" class="text-center text-muted py-4">No enrollment records found.</td></tr>@endforelse</tbody></table>{{ $enrollments->links() }}</div></div>
</div>
@endsection
