@extends('backend.layout.default')
@section('title', 'Student Report')
@section('content')
<div class="container-fluid">
<div class="d-flex justify-content-between align-items-center mb-3"><div><h4 class="mb-1">Student Report</h4><p class="text-muted mb-0">Student demographic, contact and status report.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-danger" href="{{ route('admin.reports.students.pdf', request()->query()) }}"><i class="bx bxs-file-pdf me-1"></i>PDF</a><a class="btn btn-outline-success" href="{{ route('admin.reports.students.excel', request()->query()) }}"><i class="bx bx-spreadsheet me-1"></i>Excel</a></div></div>
<div class="card"><div class="card-body"><form method="GET" class="row g-2"><div class="col-md-4"><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Student number, admission no. or name"></div><div class="col-md-2"><select class="form-select" name="gender"><option value="">All genders</option>@foreach(['male','female','other'] as $v)<option value="{{ $v }}" @selected(request('gender')===$v)>{{ ucfirst($v) }}</option>@endforeach</select></div><div class="col-md-2"><select class="form-select" name="status"><option value="">All statuses</option>@foreach(['active','inactive','graduated','transferred','withdrawn'] as $v)<option value="{{ $v }}" @selected(request('status')===$v)>{{ ucfirst($v) }}</option>@endforeach</select></div><div class="col-md-2"><button class="btn btn-primary w-100">Filter</button></div><div class="col-md-2"><a href="{{ route('admin.reports.students') }}" class="btn btn-light w-100">Reset</a></div></form></div></div>
<div class="card"><div class="card-body table-responsive"><table class="table table-hover align-middle"><thead><tr><th>#</th><th>Student No.</th><th>Admission No.</th><th>Name</th><th>Gender</th><th>DOB</th><th>Phone</th><th>Admission Date</th><th>Status</th></tr></thead><tbody>@forelse($students as $student)<tr><td>{{ $students->firstItem()+$loop->index }}</td><td>{{ $student->student_number }}</td><td>{{ $student->admission_number ?? '-' }}</td><td>{{ trim("{$student->first_name} {$student->middle_name} {$student->last_name}") }}</td><td>{{ ucfirst($student->gender ?? '-') }}</td><td>{{ optional($student->date_of_birth)->format('d M Y') ?? '-' }}</td><td>{{ $student->phone ?? '-' }}</td><td>{{ optional($student->admission_date)->format('d M Y') }}</td><td><span class="badge bg-light text-dark">{{ ucfirst($student->status) }}</span></td></tr>@empty<tr><td colspan="9" class="text-center text-muted py-4">No students found.</td></tr>@endforelse</tbody></table>{{ $students->links() }}</div></div>
</div>
@endsection
