<?php

namespace App\Http\Controllers\Admin\Wave4;

use App\Models\AdmissionApplication;
use App\Models\AcademicYears;
use App\Models\Classes;
use App\Models\Section;
use App\Services\AdmissionService;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;

class AdmissionController extends SchoolScopedController
{
    public function __construct(
        private AdmissionService $service
    ) {
    }

    /**
     * List school-scoped admission applications.
     */
    public function index(Request $request)
    {
        $schoolId = $this->schoolId();

        $items = AdmissionApplication::query()
            ->where('school_id', $schoolId)
            ->with([
                'academicYear',
                'class',
                'section',
                'student',
            ])
            ->when(
                $request->filled('status'),
                fn ($query) => $query->where(
                    'status',
                    $request->input('status')
                )
            )
            ->when(
                $request->filled('search'),
                function ($query) use ($request) {
                    $search = trim($request->input('search'));

                    $query->where(function ($q) use ($search) {
                        $q->where(
                            'application_number',
                            'like',
                            '%' . $search . '%'
                        )
                        ->orWhere(
                            'first_name',
                            'like',
                            '%' . $search . '%'
                        )
                        ->orWhere(
                            'middle_name',
                            'like',
                            '%' . $search . '%'
                        )
                        ->orWhere(
                            'last_name',
                            'like',
                            '%' . $search . '%'
                        )
                        ->orWhere(
                            'email',
                            'like',
                            '%' . $search . '%'
                        )
                        ->orWhere(
                            'phone',
                            'like',
                            '%' . $search . '%'
                        );
                    });
                }
            )
            ->latest('id')
            ->paginate(20)
            ->withQueryString();

        return view(
            'admin.wave4.admissions.index',
            compact('items')
        );
    }

    /**
     * Show create form.
     */
    public function create()
    {
        return view(
            'admin.wave4.admissions.form',
            $this->formData(new AdmissionApplication())
        );
    }

    /**
     * Create a new admission application.
     *
     * Application number is generated by AdmissionService.
     */
    public function store(Request $request)
    {
        $this->service->create(
            $this->validated($request)
        );

        return redirect()
            ->route('admin.admissions.index')
            ->with(
                'success',
                'Admission application created successfully.'
            );
    }

    /**
     * Show edit form.
     */
    public function edit(AdmissionApplication $admission)
    {
        $this->ensureSchool($admission);

        return view(
            'admin.wave4.admissions.form',
            $this->formData($admission)
        );
    }

    /**
     * Update an admission application.
     */
    public function update(
        Request $request,
        AdmissionApplication $admission
    ) {
        $this->ensureSchool($admission);

        $this->service->update(
            $admission,
            $this->validated($request)
        );

        return redirect()
            ->route('admin.admissions.index')
            ->with(
                'success',
                'Admission application updated successfully.'
            );
    }

    /**
     * Accept an admission application.
     */
    public function accept(AdmissionApplication $admission)
    {
        $this->ensureSchool($admission);

        $this->service->accept($admission);

        return back()->with(
            'success',
            'Admission application accepted.'
        );
    }

    /**
     * Convert an accepted/eligible applicant to a student.
     */
    public function convert(AdmissionApplication $admission)
    {
        $this->ensureSchool($admission);

        $student = $this->service->convertToStudent(
            $admission
        );

        return redirect()
            ->route('admin.students.show', $student)
            ->with(
                'success',
                'Applicant converted to student successfully.'
            );
    }

    /**
     * Delete an admission application.
     */
    public function destroy(AdmissionApplication $admission)
    {
        $this->ensureSchool($admission);

        abort_if(
            $admission->student_id,
            422,
            'Converted applications cannot be deleted.'
        );

        $admission->delete();

        return back()->with(
            'success',
            'Admission application deleted successfully.'
        );
    }

    /**
     * Prepare data required by create/edit form.
     */
    private function formData(
        AdmissionApplication $item
    ): array {
        $schoolId = $this->schoolId();

        return [
            'item' => $item,

            'years' => AcademicYears::query()
                ->where('school_id', $schoolId)
                ->where('is_active', 1)
                ->whereNull('deleted_at')
                ->orderByDesc('is_current')
                ->orderByDesc('start_date')
                ->get(),

            'classes' => Classes::query()
                ->where('school_id', $schoolId)
                ->where('is_active', 1)
                ->whereNull('deleted_at')
                ->orderBy('name')
                ->get(),

            'sections' => Section::query()
                ->whereHas(
                    'class',
                    fn ($query) => $query
                        ->where('school_id', $schoolId)
                        ->where('is_active', 1)
                        ->whereNull('deleted_at')
                )
                ->where('is_active', 1)
                ->whereNull('deleted_at')
                ->orderBy('name')
                ->get(),
        ];
    }

    /**
     * Validate admission form input.
     *
     * application_number is intentionally absent because
     * AdmissionService generates it server-side.
     */
    private function validated(Request $request): array
    {
        $schoolId = $this->schoolId();

        return $request->validate([
            'first_name' => [
                'required',
                'string',
                'max:255',
            ],

            'middle_name' => [
                'nullable',
                'string',
                'max:255',
            ],

            'last_name' => [
                'required',
                'string',
                'max:255',
            ],

            'date_of_birth' => [
                'nullable',
                'date',
                'before:today',
            ],

            'gender' => [
                'nullable',
                Rule::in([
                    'male',
                    'female',
                    'other',
                ]),
            ],

            'phone' => [
                'nullable',
                'string',
                'max:50',
            ],

            'email' => [
                'nullable',
                'email',
                'max:255',
            ],

            'address' => [
                'nullable',
                'string',
                'max:5000',
            ],

            'guardian_name' => [
                'nullable',
                'string',
                'max:255',
            ],

            'guardian_phone' => [
                'nullable',
                'string',
                'max:50',
            ],

            'guardian_email' => [
                'nullable',
                'email',
                'max:255',
            ],

            'guardian_relationship' => [
                'nullable',
                'string',
                'max:100',
            ],

            'academic_year_id' => [
                'nullable',
                'integer',
                Rule::exists('academic_years', 'id')
                    ->where(
                        fn ($query) => $query
                            ->where('school_id', $schoolId)
                    ),
            ],

            'class_id' => [
                'nullable',
                'integer',
                Rule::exists('classes', 'id')
                    ->where(
                        fn ($query) => $query
                            ->where('school_id', $schoolId)
                    ),
            ],

            'section_id' => [
                'nullable',
                'integer',
                Rule::exists('sections', 'id'),
            ],

            'status' => [
                'required',
                Rule::in([
                    'draft',
                    'submitted',
                    'under_review',
                    'accepted',
                    'rejected',
                    'converted',
                ]),
            ],

            'notes' => [
                'nullable',
                'string',
                'max:10000',
            ],

            'applied_at' => [
                'nullable',
                'date',
            ],
        ]);
    }
}