<!doctype html>
<html>
<head>
    <meta charset="utf-8">

    <title>{{ $title }}</title>

    <style>
        @page {
            margin: 25px 20px;
        }

        body {
            font-family: DejaVu Sans, Arial, sans-serif;
            font-size: 9px;
            color: #222;
        }

        h2 {
            margin: 0 0 12px 0;
            font-size: 16px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #ccc;
            padding: 5px;
            text-align: left;
            vertical-align: top;
        }

        th {
            background: #f2f2f2;
            font-weight: bold;
        }

        tr {
            page-break-inside: avoid;
        }
    </style>
</head>

<body>

@php
    /*
    |--------------------------------------------------------------------------
    | Report Headings
    |--------------------------------------------------------------------------
    |
    | These headings MUST remain in exactly the same order as the
    | numeric row arrays generated by ReportsController.
    |
    */

    $headingMap = [

        /*
        |--------------------------------------------------------------------------
        | Students
        |--------------------------------------------------------------------------
        */
        'Student Report' => [
            'Student Number',
            'Admission Number',
            'Student Name',
            'Gender',
            'Date of Birth',
            'Phone',
            'Admission Date',
            'Status',
        ],


        /*
        |--------------------------------------------------------------------------
        | Enrollment
        |--------------------------------------------------------------------------
        */
        'Enrollment Report' => [
            'Enrollment Number',
            'Student',
            'Academic Year',
            'Term',
            'Class',
            'Section',
            'Enrollment Date',
            'Status',
        ],


        /*
        |--------------------------------------------------------------------------
        | Academic Performance
        |--------------------------------------------------------------------------
        */
        'Academic Performance Report' => [
            'Student',
            'Examination',
            'Academic Year',
            'Term',
            'Total Score',
            'Average',
            'Grade',
            'Position',
            'Status',
        ],


        /*
        |--------------------------------------------------------------------------
        | Student Attendance
        |--------------------------------------------------------------------------
        |
        | ReportsController order:
        |
        | Date
        | Student
        | Class
        | Section
        | Course
        | Status
        | Remarks
        |
        */
        'Attendance Report' => [
            'Date',
            'Student',
            'Class',
            'Section',
            'Course',
            'Status',
            'Remarks',
        ],


        /*
        |--------------------------------------------------------------------------
        | Staff Report
        |--------------------------------------------------------------------------
        */
        'Staff Report' => [
            'Date',
            'Staff',
            'Status',
            'Check In',
            'Check Out',
            'Remarks',
        ],


        /*
        |--------------------------------------------------------------------------
        | Staff Attendance
        |--------------------------------------------------------------------------
        |
        | ReportsController order:
        |
        | Date
        | Staff Number
        | Staff
        | Status
        | Check In
        | Check Out
        | Remarks
        |
        */
        'Staff Attendance Report' => [
            'Date',
            'Staff Number',
            'Staff',
            'Status',
            'Check In',
            'Check Out',
            'Remarks',
        ],
    ];


    /*
    |--------------------------------------------------------------------------
    | Get headings for current report
    |--------------------------------------------------------------------------
    */

    $headings = $headingMap[$title] ?? [];


    /*
    |--------------------------------------------------------------------------
    | Fallback
    |--------------------------------------------------------------------------
    |
    | If a future report is added without being registered above,
    | generate generic headings based on the number of columns.
    |
    */

    if (empty($headings) && !empty($rows)) {

        $columnCount = count($rows[0]);

        for ($i = 0; $i < $columnCount; $i++) {
            $headings[] = 'Column ' . ($i + 1);
        }
    }
@endphp


<h2>{{ $title }}</h2>


<table>

    <thead>

        <tr>

            @foreach($headings as $heading)

                <th>
                    {{ $heading }}
                </th>

            @endforeach

        </tr>

    </thead>


    <tbody>

        @forelse($rows as $row)

            <tr>

                @foreach($row as $value)

                    <td>
                        {{ $value ?? '-' }}
                    </td>

                @endforeach

            </tr>

        @empty

            <tr>

                <td colspan="{{ max(count($headings), 1) }}">
                    No records found.
                </td>

            </tr>

        @endforelse

    </tbody>

</table>


</body>
</html>